### ISSUE TITLE
Некорректно забирает сообщения с https://tgistation.ru/

### ISSUE THREAD

**Issue by ptah-alexs** [gl00my/ii-go#2]
Версия из master собрана go 1.23

```
$ ./ii-tool fetch https://tgistation.ru nn
INFO: 2024/11/20 14:35:03 Start fetcher(s) for https://tgistation.ru
INFO: 2024/11/20 14:35:03 https://tgistation.ru tgi.ordos.blog: no valid MsgId (0qHMnIAS8VIKaP0R4z1EWWJMSs64ahkXmB48XFFPzgVVoi59vFiK02o0wClXUspXqgX1XXMQmIuN8psyKk7THljLtcNMF9crl5GZ)
```
```
$ curl https://tgistation.ru/u/e/tgi.ordos.blog/-1:1
tgi.ordos.blog
0qHMnIAS8VIKaP0R4z1E
WWJMSs64ahkXmB48XFFP
zgVVoi59vFiK02o0wClX
UspXqgX1XXMQmIuN8psy
Kk7THljLtcNMF9crl5GZ
```

И такая ситуация со всеми эхами.

**Comment by hugeping** [comment]
Дело в том что tgistation.ru не поддерживает u/e слайсы. Например: https://tgistation.ru/u/e/idec.talks/-1:1 возвращает весь список. Это приводит к тому, что адаптивный фетч (вкл. по умолчанию) работает неправильно.
Для этих станций придётся указать режим force в фетчере (кажется, параметр -f)

Это не проблема ii-go

**Comment by ptah-alexs** [comment]
Спасибо
